### ISSUE TITLE
Add word wrapping support

### ISSUE THREAD

**Issue by raklaptudirm** [shoumodip/keimeno#1]
I am currently unable to compile this, due to `ncurses` not supporting Windows, but from reading your code it does not seem like it accounts for word wrapping, or even horizontal scrolling (two solutions to the same problem).

**Comment by shoumodip** [comment]
I don't think I understand what you mean about ncurses not supporting windows. I mean, it is a C library which only sends escape codes (literally a cstr) according to a terminfo database. It should, *in theory*, support anything and everything under the sun. Do you mean your terminal emulator doesn't support it?

Scrolling *is* supported in keimeno. There is a field in the `Editor` structure named `anchor`. It is a vector which points to the point in the buffer to start rendering from in the terminal. Check out `editor.h` and `editor.c`.

I personally do not like word wrapping, so that is something I don't thing I will implement. Pull requests are welcome tho.

Cheers :)

**Comment by raklaptudirm** [comment]
I saw `anchor`. It implements horizontal scrolling, and i was talking about vertical scrolling, which will be required for long lines *if* you do not implement word wrapping. It may be an easier option, as for word wrapping, you will need a whole intermediate representation to map the cursor to your file (and it is not fun, trust me).

About the `ncurses` thing I though so. But then I found this unix stackexchange thread which said how they were trying to port `ncurses` to Windows, so I thought it may be doing something else. But turns out they were wrong. I will try to get it running.

**Comment by shoumodip** [comment]
Check it out again. `anchor` is a vector (vector as in math, not as in dynamic array, damn it C++), It provides the rendering point for both the x and y coordinates. So scrolling along **both axes** (fun fact: plural of `axis`) is implemented.

BTW, even if you don't have word wrapping, you still need an intermediate cursor to account for the fact that tab characters and control characters don't have a width of 1 character. (Well the tab *may* be 1 character wide, if you are a psychopath, I guess)

If I may, I would suggest [Alacritty](https://github.com/alacritty/alacritty) as an ANSI-compatible terminal for trying for keimeno. It is what I am using myself, and it is cross-platform. It is written in Rust, so need to rewrite it, I guess ;)

**Comment by raklaptudirm** [comment]
My terminal is not the problem actually. I use `cmder` built on `ConEmu`, and everything works well. The problem is my inexperience in dealing with packages in c :(

Also, I know what a vector means lol.

**Comment by shoumodip** [comment]
I found [this](https://e-l.unifi.it/mod/resource/view.php?id=241598) on the internet about installing ncurses. Maybe it might help?.

>  The problem is my inexperience in dealing with packages in c :(

Lol, there **are no** packages in C. It's insane, right? You basically "deal with packages" like this:
- Download a library from the internet, hope it's not malware
- Link it in the compilation stage, cross your fingers, and pray it doesn't cause a conflict
- If it causes a conflict, you abandon the whole idea
- If you don't abandon the whole idea and you intend to fix the conflicts, may god have mercy on your soul, hair, and sanity

**Comment by raklaptudirm** [comment]
I like to refer to them as packages to prevent programming language conflicts in my brain basically.

**Comment by shoumodip** [comment]
I am closing this issue then. Like I mentioned, word wrapping is not something I intend to implement. PRs are welcome!
